#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config border_width         1

bspc config window_gap           0

bspc config label-empty = "" 

# Colors 
bspc config focused_border_color \#ffffff
bspc config normal_border_color \#6k7689

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a viewnior state=floating

xsetroot -cursor_name left_ptr

$HOME/.config/bspwm/autostart
