[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 13.5

[font.bold]
family = "FiraMono Nerd Font Mono"

[font.normal]
family = "FiraMono Nerd Font Mono"
style = "medium"

[window]
title = "Hacking"
